### ISSUE TITLE
Can we  Resize (width&height) the images with current resolution ?

### ISSUE THREAD

**Issue by abada** [spatie/pdf-to-image#1]
Can we  Resize (width&height) the images with current resolution ?

**Comment by freekmurze** [comment]
This package only does the converting from pdf to image. If you need to manipulate the image further, take a look at [Intervention](http://image.intervention.io/)

**Comment by abada** [comment]
Thank you ,

I tried 

~~~
$imagick->scaleImage(100,0);
~~~

and working fine :+1: 

Thanks for amazing calss

**Comment by garak** [comment]
I had the same issue and I resolved using `$pdf->setResolution(85);`
