### ISSUE TITLE
Requested FirstPage is greater than the number of pages in the file

### ISSUE THREAD

**Issue by amadohin** [spatie/pdf-to-image#100]
Hi I'm getting this error:

Fatal error: Uncaught ImagickException: PDFDelegateFailed `[ghostscript library 9.23] -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=bmpsep8" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r144x144" -dUseCIEColor -dFirstPage=12 -dLastPage=12 "-sOutputFile=C:/Users/DESARR~1/AppData/Local/Temp/magick-2980u-2q1FXLrAYr%d" "-fC:/Users/DESARR~1/AppData/Local/Temp/magick-29804IzzgG7afazS" "-fC:/Users/DESARR~1/AppData/Local/Temp/magick-2980TSNyiXIaLZrd": Requested FirstPage is greater than the number of pages in the file: 11 No pages will be processed (FirstPage > LastPage). ' @ error/pdf.c/ReadPDFImage/801 in C:\xampp\htdocs\PDF\vendor\spatie\pdf-to-image\src\Pdf.php:239 Stack trace: #0 C:\xampp\htdocs\PDF\vendor\spatie\pdf-to-image\src\Pdf.php(239): Imagick->readimage('C:\\xampp\\tmp\\ph...') #1 C:\xampp\htdocs\PDF\vendor\spatie\pdf-to-image\src\Pdf.php(178): Spatie\PdfToImage\Pdf->getImageData('C:/xampp/htdocs...') #2 C:\xampp\htdocs\PDF\php\process.php(92): Spati in C:\xampp\htdocs\PDF\vendor\spatie\pdf-to-image\src\Pdf.php on line 239

The resulting images is correct but are in black and white 

The PDF has 11 pages, if I try setting 2 pages it works fine but the images are too in black and white.

I have working with PDF's with 40 pages with no problem.

I have tried change the format too, but it doest work.

**Comment by YeluVimal** [comment]
I also have the same problem.

**Comment by bulgariamitko** [comment]
same error here
