### ISSUE TITLE
Postscript delegate failed: No such file or directory

### ISSUE THREAD

**Issue by mikerodham** [spatie/pdf-to-image#103]
**THIS IS NOT AN ISSUE WITH THIS PACKAGE**
This is just in case anyone runs in to this issue in the future, because there wasn't really a lot of help on google. I hope this helps somebody.

**My Use Case:**
I had written some code to convert a pdf to an image, then manipulate that image to attach further images/text so users could sign a pdf with their details and just a record of proof that the PDF was signed.

**Problem**
I had the code all setup, working wonderfully. Closed down my laptop at the end of the day, and learned through the night it had created over 1,000 files. I opened up my laptop this morning and came to the following error:

**Error**

file: "/path/to/my/vendor/directory/spatie/pdf-to-image/src/Pdf.php"
line: 169
message: "Postscript delegate failed `path/to/public/directory/attachments/somefilename.pdf` : No such file or directory @ error/pdf.c/ReadPDFImage/677"

Specifically: ` $imagick->readImage(sprintf('%s[%s]', $this->pdfFile, $this->page - 1));`

**Debugging**
I'm using this package with Laravel 4.2, and the above was the only error I was getting however I was absolutely 100% sure file exists, I followed the path in my terminal exactly, file found, permissions were fine. I looked through NGINX error log, nothing relative. Laravel error log, the error above. Okay, so I restart nginx just in-case something funny is going on, still hitting the error. As a last resort, restarted php5-fpm, result. Error has disappeared.

**Solution**
`sudo service php5-fpm restart`

**Comment by freekmurze** [comment]
Thanks for posting this!
