### ISSUE TITLE
Feature request - Change the image file name

### ISSUE THREAD

**Issue by marabesi** [spatie/pdf-to-image#107]
I am using the lib currently and I'd like to have the ability to set the saved image name. Right now, it is saved always using the name `1`.

I started to work on this feature (https://github.com/spatie/pdf-to-image/pull/106) but @freekmurze suggested to change the code to pass a second argument to the saveImage method instead.

**Comment by christophe-mailfert** [comment]
So ?

**Comment by freekmurze** [comment]
Gonna keep this like it is for now.

**Comment by MateusFGoncalves** [comment]
Hey guys, you can change the file name! Just pass the file path along with the name at the time of saving!

Example:

`
            $pdf = new \Spatie\PdfToImage\Pdf(storage_path('app/user/doc/').$new_doc); `
            `$pdf->saveImage(storage_path('app/pacientes/documentos/').$pac_id . '/thumbnails/'.$name_file);`

$name_file is the name I want for my file
