### ISSUE TITLE
Giving class a blob rather than a file name?

### ISSUE THREAD

**Issue by fredbradley** [spatie/pdf-to-image#109]
Hello. 

Is there a way to use this by give the Pdf class a blob of a PDF rather than a file path? 

I want to create an image from a pdf saved in the database on the fly without having to save it to the filesystem first.

**Comment by freekmurze** [comment]
It doesn't accept a blob now, but if the code do to this is simple, I'd accept a fully tested PR ( an with an updated readme) that adds this to the package.
