### ISSUE TITLE
Resources exhausted when saving images

### ISSUE THREAD

**Issue by maurocasas** [spatie/pdf-to-image#110]
I'm trying to save a 2-page PDF using saveAllPagesAsImages method, and I tried iterating aswell through the pages, but I always come to the same place:

`In Pdf.php line 239: cache resources exhausted /tmp/magick-30670fyAqlflWj7nc1 @ error/cache.c/OpenPixelCache/3984`

Any idea why this might be happening?

**Comment by freekmurze** [comment]
I guess this has something to do with the server where you are running this on. Perhaps it's out of memory?
