### ISSUE TITLE
Failed to open Blob / PDF doesn't exist

### ISSUE THREAD

**Issue by YuriZakaria** [spatie/pdf-to-image#115]
I am using Laravel 5.5 with PHP 7.2 over XAMPP and Imagick, ghostscript installed.

When I try to use this:
```
        $book = Book::create([
          'name' => $request['name'],
          'author_id' => $request['author_id'],
          'path' => $request['path'],
          'file' => $request['file'],
        ]);
        $pathToImage = "public/bookthumbs/";
        $file = $book->path."/".$book->file;
        $pdf = new \Spatie\PdfToImage\Pdf($file);
        $pdf->saveImage($pathToImage);
        //
        // $imagick = new \Imagick($file[0]);
        // $imagick->setImageFormat('jpg');
        // file_put_contents($pathToImage, $imagick);

        $book->bgenres()->attach($request['bgenre_id']);
        return $file;
```

it gives me he following error:

`Spatie \ PdfToImage \ Exceptions \ PdfDoesNotExist `

`(Spatie\\PdfToImage\\Exceptions\\PdfDoesNotExist(code: 0):  at C:\\xampp\\htdocs\\lab\\aziz\\vendor\\spatie\\pdf-to-image\\src\\Pdf.php:41)`

` C:\\xampp\\htdocs\\lab\\aziz\\app\\Http\\Controllers\\BooksController.php(105): Spatie\\PdfToImage\\Pdf->__construct('storage/app/pub...')`

the `$file` path returned is `public/books1/tests/43om.pdf`

knowing that the files exist in both places, `storage/app/public/books1/tests/...` and in `public/books1/tests/...`

if I tried to use the original code of imagick it displays:

`Unable to OpenBlob No Such file or directory.`

I know there's a problem in my path or probably the code, but can anyone help?

**Comment by freekmurze** [comment]
That exception is being thrown if the file doesn't exist, make sure you passed it the right path.

**Comment by YuriZakaria** [comment]
I solved it by adding the public_path($file)
thanks for the help

**Comment by satyabratapanigrahi** [comment]
$book = Book::create([
          'name' => $request['name'],
          'author_id' => $request['author_id'],
          'path' => $request['path'],
          'file' => $request['file'],
        ]);
        $pathToImage = "public/bookthumbs/";
        $file = $book->path."/".$book->file;
        $pdf = new \Spatie\PdfToImage\Pdf(public_path($file));
        $pdf->saveImage($pathToImage);
        //
        // $imagick = new \Imagick($file[0]);
        // $imagick->setImageFormat('jpg');
        // file_put_contents($pathToImage, $imagick);

        $book->bgenres()->attach($request['bgenre_id']);
        return $file;
