### ISSUE TITLE
ext-imagick required. 

### ISSUE THREAD

**Issue by Salman937** [spatie/pdf-to-image#117]
I am adding this library to my Laravel project when I hit the command then I am getting an error. please help how I can move further.

Problem 1
    - spatie/pdf-to-image 1.8.1 requires ext-imagick * -> the requested PHP extension imagick is missing from your system.
    - spatie/pdf-to-image 1.8.0 requires ext-imagick * -> the requested PHP extension imagick is missing from your system.
    - Installation request for spatie/pdf-to-image ^1.8 -> satisfiable by spatie/pdf-to-image[1.8.0, 1.8.1].

**Comment by freekmurze** [comment]
Install imagick to fix this.

**Comment by Salman937** [comment]
I am using mac i have install it but still facing the problem can you give me some steps @freekmurze
