### ISSUE TITLE
Using saveImage on PDF makes background black

### ISSUE THREAD

**Issue by AuditeMarlow** [spatie/pdf-to-image#12]
I load up a PDF using `$pdf = new Pdf($pathToPdf);` and save it using `$pdf->saveImage($pathToUploads);`. It generates an image, but the background turns to black. Maybe this has to do with transparency?

**Comment by freekmurze** [comment]
Probably something to do with transparency yes...

I'd accept a PR that fixes this.

**Comment by AuditeMarlow** [comment]
Figured this happens when the PDF has multiple pages and you try to save it without looping through the pages.

**Comment by adilsaeed31** [comment]
HI, 

Yes I'm facing the same issue i have multiple pages pdf file, when i convert it, it give me black background  instead of white, any solution so far ?

Thanks
Adil

**Comment by AuditeMarlow** [comment]
You loop through the PDF pages to save each page individually.

    for ($i = 1; $i <= $pdf->getNumberOfPages(); $i++) {
        $pdf->setPage($i)->setOutputFormat('png')->saveImage('path/to/image.png');
    }

You can in turn also decide yourself what page number you want to save.

    $i = 1;
    $pdf->setPage($i)->setOutputFormat('png')->saveImage('path/to/image.png');

**Comment by adilsaeed31** [comment]
Thanks for this, that i have already did, but can't save single image with all pages images is there any way for this.

Thanks for your help so far.

**Comment by BenjaminRehn** [comment]
i did a short look, and as i can see Imagick is used, try to  use
flattenImages(); that should do the trick

**Comment by BenjaminRehn** [comment]
flattenImages() was just removed as i can see, now it's
$image->mergeImageLayers(\Imagick::LAYERMETHOD_FLATTEN);

**Comment by BenjaminRehn** [comment]
Try this ;-)
#13

**Comment by piarson** [comment]
Same issue persists (transparent background) when trying to save as PNG

**Comment by freekmurze** [comment]
Closing this for now, I accept PR's that make this package more stable.
