### ISSUE TITLE
I tried to install this packages in my project on windows then return this error

### ISSUE THREAD

**Issue by Iso-Doss** [spatie/pdf-to-image#121]
I tried to install this packages in my project on windows then return this error

composer require spatie/pdf-to-image

Problem 1 - spatie/pdf-to-image 1.8.1 requires ext-imagick * -> the requested PHP extension imagick is missing from your system. - spatie/pdf-to-image 1.8.0 requires ext-imagick * -> the requested PHP extension imagick is missing from your system. - Installation request for spatie/pdf-to-image ^1.8 -> satisfiable by spatie/pdf-to-image[1.8.0, 1.8.1].

To enable extensions, verify that they are enabled in your .ini files: - C:\wamp64\bin\php\php7.1.16\php.ini You can also run php --ini inside terminal to see which files are used by PHP in CLI mode.

Installation failed, deleting ./composer.json.

**Comment by freekmurze** [comment]
Please install the necessary extension.

**Comment by Iso-Doss** [comment]
http://prntscr.com/n3p24w

**Comment by Iso-Doss** [comment]
Hi, 
Below an image that shows that I have the imagick extension enable on my server but I still can not install the library

<img width="960" alt="Screenshot_430" src="https://user-images.githubusercontent.com/21062528/55140886-68845700-5139-11e9-9ea3-a443fcafba0b.png">
