### ISSUE TITLE
Add env[PATH] = /usr/local/bin:/usr/bin:/bin to php-fpm.conf

### ISSUE THREAD

**Issue by lstables** [spatie/pdf-to-image#124]
But still getting the following error

````
FailedToExecuteCommand `'gs' -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 - ......
````

Any ideas on this please and I am using PHP7.1 with Laravel Valet.

**Comment by lstables** [comment]
After a reboot of my mac I get `Imagick::__construct(): stream does not support seeking` now

**Comment by lstables** [comment]
It appears that it doesn't like reading from S3, so saved it locally and all works. But I do want this to come S3 if possible, any suggestions?

**Comment by freekmurze** [comment]
Don't have experience or a need to make this work with S3, so can't help you with this.

If there's something the package can do to enable this, send a PR with tests.
