### ISSUE TITLE
setLayerMethod doesn't accept null

### ISSUE THREAD

**Issue by KarlChiraz** [spatie/pdf-to-image#125]
Hello! So as per the description of this function
* Sets the layer method for Imagick::mergeImageLayers()
* If int, should correspond to a predefined LAYERMETHOD constant.
* If null, Imagick::mergeImageLayers() will not be called.

it should be able to accept a layer value of null how ever it doesn't since null is not an int..

**Comment by freekmurze** [comment]
Is there a bug atm? Feel free to submit a PR with tests for this.
