### ISSUE TITLE
Upload With FTP

### ISSUE THREAD

**Issue by cakerimov** [spatie/pdf-to-image#126]
Hello its not issue, i need upload converted image files to ftp not to local directory, But FTP Connection not working here, i tried insert data to mysql, but nothing inserted. can anybody help me ?

public function saveImage($pathToImage)
    {
        if (is_dir($pathToImage)) {
            $pathToImage = rtrim($pathToImage, '\/').DIRECTORY_SEPARATOR.$this->page.'.'.$this->outputFormat;
        }

        $imageData = $this->getImageData($pathToImage);

        return file_put_contents($pathToImage, $imageData) !== false;
        
                    //ftp start

                    $ftp_server = "SERVER_URL";
                    
                    //$file = $imageData;
                    $file = $pathToImage;
                    $remote_file = 'uploads/' . $file;
                    $conn_id = ftp_connect($ftp_server);
                    $login_result = ftp_login($conn_id, "USERNAME", "PASSWORD");
                    if (ftp_put($conn_id, $remote_file, $file, FTP_ASCII)) {
                        echo "UPLOADED! $file\n";
                    } else {
                        echo "ERROR! $file\n";
                    }

                    //ftp end
        

    }

**Comment by freekmurze** [comment]
FTP is out of scope for this package.
