### ISSUE TITLE
Make $pdfFile param nullable in \Spatie\PdfToImage\Pdf::__construct

### ISSUE THREAD

**Issue by 4n70w4** [spatie/pdf-to-image#127]
It will be usefull to get a instance of `PdfToImage\Pdf` throught a DI container.
And add separate setter for `\Spatie\PdfToImage\Pdf::$pdfFile`.

**Comment by freekmurze** [comment]
I'm going to leave this like it is for now.

**Comment by 4n70w4** [comment]
@freekmurze why are you closed or unsolved issue? What is this methodology?
