### ISSUE TITLE
Convert pdf (first page) -> jpg is too slow

### ISSUE THREAD

**Issue by Arkos13** [spatie/pdf-to-image#129]
Can you help with one problem ? The server takes a long time to process a file with a size of 20mb (that is, saving the first page as jpg) - 1.2 minutes. I have already read about caching to disk, which is much slower than caching to memory and need to use Ghostscript. But it is already used in this library judging from the description.

**Comment by freekmurze** [comment]
I’m sorry, I don’t have time to help on specific projects. Feel free to send a PR if you find this package is doing something wrong
