### ISSUE TITLE
PHP：Failed to read the file

### ISSUE THREAD

**Issue by hoseadevops** [spatie/pdf-to-image#131]
LOG

   **** This file had errors that were repaired or ignored.
   **** The file was produced by:
   **** >>>> Mac OS X 10.12.6 Quartz PDFContext <<<<
   **** Please notify the author of the software that produced this
   **** file that it does not conform to Adobe's published PDF
   **** specification.

**Comment by freekmurze** [comment]
This package uses imagick to read pdfs. Open up an issue at their repo.
