### ISSUE TITLE
Colors are slightly distorted in the converted image.

### ISSUE THREAD

**Issue by rpelletierrefocus** [spatie/pdf-to-image#132]
During the conversion process the colors are becoming slightly distorted. Is there anything I can do to remedy this?

You can see what I am talking about below.
The left is the converted image, the right is the original pdf.

https://imgur.com/l09YkUc

Thank you.

**Comment by Houbsi** [comment]
I would presume that there is a colorprofile in your original image.
I had issues with colorprofiles attached to the original file cause conversions issues all the time.
