### ISSUE TITLE
Problem with large file.

### ISSUE THREAD

**Issue by truechernyshov** [spatie/pdf-to-image#138]
Server is down with 503 error when loading big pdf(8Mb, 40 pages).
It's because you puting file in construct method Imagick.

`$this->imagick = new Imagick($pdfFile);`

But why whole file if i need only one page. In method getImageData there is instruction that page is need use for generate preview.

`$this->imagick->readImage(sprintf('%s[%s]', $this->pdfFile, $this->page - 1));`

If you need read all file don't indicate index of page. Like this:

`$this->imagick->readImage($this->pdfFile);`

After then i deleted file from constructor Imagick

`$this->imagick = new Imagick();`

And all works fine. If you want pick another page there is method setPage

**Comment by freekmurze** [comment]
I'd accept a test that fixes this. Alle current tests should pass.

**Comment by ArroWsGM** [comment]
@freekmurze,  can you please review this PR #171

**Comment by patinthehat** [comment]
For [version v3.0](https://github.com/spatie/pdf-to-image/releases/tag/3.0.0), I ran tests against significantly larger PDFs without encountering any errors. Please reopen an issue if you are still experiencing the error after upgrading. Thanks! :+1:
