### ISSUE TITLE
Wrong number of pages for native PDF

### ISSUE THREAD

**Issue by Dylan-Duault** [spatie/pdf-to-image#145]
Hello !

I'm having issues in a production environment with pdf-to-image, the package doesn't detect the good amount of pages in some files.

The issue is very rare, and happens in less than 1% of the time and only with native PDFs

See this issue #71 

Thank you,

**Comment by Blum** [comment]
Hello, 
for me 

`$pdf->getNumberOfPages()` 

always returns 1, in 100% of the PDFs I'm trying with.
And also when I try $pdf->setPage(2), I'm getting: 

> Spatie\PdfToImage\Exceptions\PageDoesNotExist: Page 2 does not exist  

The PDF document I'm passing has 15 pages actually.

I could use some clue here..

Thanks

**Comment by ShezanZahid** [comment]
Same issue. When using 
`$pdf->getNumberOfPages()`
Always getting number of page 1.  No matter what pdf it is 1 page or 30 page it always showing one.
Even i cant use 
`$pdf->setPage(2)`
show page 2 do not exist.

**Comment by mohaedismaiel** [comment]
I also have the same problem. How can I do this?

**Comment by GuillaumeLeon** [comment]
I have the same problem, anyone figured this out?

**Comment by amarruda** [comment]
Hi. The same for me.

**Comment by Blum** [comment]
I ended up using just Imagick();
```php
<?php
$im = new \Imagick();
$im->pingImage('file.pdf');
$pagesCount = $im->getNumberImages();
```

**Comment by vhcraig** [comment]
Hi all,

When installing using `composer require spatie/pdf-to-image` it appears to default to version `v2.x-dev`, which is obviously wrong.

To fix this simply specify the version (which you should be doing for production builds anyways) by running the following: `composer remove spatie/pdf-to-image && composer require spatie/pdf-to-image:2.0.1`

Everything should then function as expected. Hope this helps!

**Comment by amarruda** [comment]
Works for me. Thanks

> Hi all,
> 
> When installing using `composer require spatie/pdf-to-image` it appears to default to version `v2.x-dev`, which is obviously wrong.
> 
> To fix this simply specify the version (which you should be doing for production builds anyways) by running the following: `composer remove spatie/pdf-to-image && composer require spatie/pdf-to-image:2.0.1`
> 
> Everything should then function as expected. Hope this helps!

Works for me. Thanks. Just one note: did the changes post on https://github.com/spatie/laravel-medialibrary/issues/1268#issuecomment-429928562

**Comment by ananthakumar841** [comment]
> Works for me. Thanks
> 
> > Hi all,
> > When installing using `composer require spatie/pdf-to-image` it appears to default to version `v2.x-dev`, which is obviously wrong.
> > To fix this simply specify the version (which you should be doing for production builds anyways) by running the following: `composer remove spatie/pdf-to-image && composer require spatie/pdf-to-image:2.0.1`
> > Everything should then function as expected. Hope this helps!
> 
> Works for me. Thanks. Just one note: did the changes post on [spatie/laravel-medialibrary#1268 (comment)](https://github.com/spatie/laravel-medialibrary/issues/1268#issuecomment-429928562)

hi amarruda i try to install  composer require spatie/pdf-to-image:2.0.1 i get error spatie/pdf-to-image 2.0.1 requires ext-imagick * -> the requested PHP extension imagick is missing from your system. $pdf->getNumberOfPages()
Always getting number of page

**Comment by arunm-zersys** [comment]
@vhcraig it needs Imagick installed, or else it won't work. Installing those in mac is hell of a work .
