### ISSUE TITLE
Cannot save Image

### ISSUE THREAD

**Issue by jaypee888** [spatie/pdf-to-image#146]
Hi, 

I cannot save a single image from my loop. I'm using xampp. Please help. 

 This is my code.
$full_dir = 'uploads/';
$format = 'png'; 
$folder = base_path('/public/'.$full_dir.'pages/');  
$quality = 100; 
for($page=1; $page<=$pdf->getNumberOfPages(); $page++)  { 
 $page_save_filename = $folder.$page.'.'.$format;  
 $pdf->setPage($page);
 $pdf->setOutputFormat($format);
 //$pdf->setCompressionQuality($quality);
 $pdf->saveImage($page_save_filename);  
}

looks like $pdf->saveImage($page_save_filename);    is executed. but there's no error.

**Comment by vhcraig** [comment]
I know I'm a little late to the party, but hope this helps:

Base on the the function `base_path` I assume you are using Laravel. By adding a slash in front of `public`, it creates a double slash in the path, example: 
`/var/www/example-site//public/uploads/pages/`

So change this: 
`$folder = base_path('/public/'.$full_dir.'pages/');`

To this:
`$folder = base_path('public/'.$full_dir.'pages/');`

Additionally, ensure the paths exist. I'm not sure if it is meant to create the directory for you, so I'm not sure if this is a permission issue, I haven't looked into it.

Lastly, there is no need to set the format using a method as I believe it defaults as it is in the name.

See the complete code I've tested and is working:
```
$uploadsDir = 'uploads/';
$folder = base_path('public/' . $uploadsDir . 'pages/');
$quality = 100;

for($page = 1; $page <= $pdf->getNumberOfPages(); $page ++) {
    $pageSaveFilename = $folder . $page . '.png';
    $pdf->setPage($page)
        ->setCompressionQuality($quality)
        ->saveImage($pageSaveFilename);
}
```
