### ISSUE TITLE
Potential Versioning Issue

### ISSUE THREAD

**Issue by vhcraig** [spatie/pdf-to-image#151]
Hi,

When installing using `composer require spatie/pdf-to-image`, it appears to be defaulting to version `v2.x-dev`. This version appears to rank higher than all other versions and falls within the constraint `^2.0`. See example:
![image](https://user-images.githubusercontent.com/52801576/82611057-f1711400-9bbf-11ea-8b26-2eefa374b7c4.png)

I may be talking nonsense, but can someone please confirm?

A side effect of this can be seen here: https://github.com/spatie/pdf-to-image/issues/145#issuecomment-632368119

**Comment by freekmurze** [comment]
The rank has no effect to which version composer selects for installing. 

Try adding `prefer-stable` to your composer.json.
Example: https://github.com/spatie/freek.dev/blob/master/composer.json#L128

**Comment by vhcraig** [comment]
Ah, that makes sense. Thanks Freek!

**Comment by vhcraig** [comment]
Just a quick one @freekmurze, I checked and `prefer-stable` was set to `true`. I am sure I'm not the only one and why this issue exists: https://github.com/spatie/pdf-to-image/issues/145
