### ISSUE TITLE
Commercial use of the package with GhostScript

### ISSUE THREAD

**Issue by patsa** [spatie/pdf-to-image#152]
GhostScript is licensed under the GPLA license, which means any commercial product that uses it within it's source code, needs to adhere to that license. 
As pdf-to-image uses GS through ImageMagick, that also counts when using pdf-to-image itself. Or am I wrong on this?

If this is true, I think it should be mentioned within the Readme, that because of the GPLA license of GS a commercial license is required to be bought from Artifex.
The importance of this stems from the fact, that there have already been court disputes about not following the license restrictions:
https://news.ycombinator.com/item?id=19364505

Please correct me on this one, if I'm wrong.

PS
I'm not a lawyer and I can't give anyone any legal advice.

**Comment by freekmurze** [comment]
I'm also not a lawyer, but on their website it is mentioned:

```
Ghostscript is a copyrighted work; it is not shareware or in the public domain. Versions entitled GPL Ghostscript are distributed with the GNU Affero General Public License, which allows free use, and free copying and redistribution under certain conditions (including, in some cases, commercial distribution).
```

We also don't change its source code.

Leaving it like this for now.
