### ISSUE TITLE
$this->numberOfPages = $this->imagick->getNumberImages(); causes Maximum execution time of 30 seconds exceeded 

### ISSUE THREAD

**Issue by trevorpan** [spatie/pdf-to-image#153]
Have laravel medialibrary installed. It works fine for single page files. However a four page 8.5MB (and a smaller 2.5MB of the same file) pdf throws this:

`Maximum execution time of 30 seconds exceeded` or `502 Bad Gateway` 

Single page files do not throw the error.

https://github.com/spatie/pdf-to-image/issues/16
https://github.com/spatie/laravel-medialibrary/issues/1271
http://www.imagemagick.org/discourse-server/viewtopic.php?t=19087

Tried out a ton possible issues, but the error always comes back to a method in `vendor/spatie/pdf-to-image/src/Pdf.php` file. 

Here's the versions I'm using:         
"spatie/laravel-medialibrary": "^7",
"spatie/pdf-to-image": "2.0.1",

**Laravel 7**
GPL Ghostscript 9.50 (2019-10-15)

**php.ini**
upload_max_filesize = 32M
max_file_uploads = 20
post_max_size = 128M
memory_limit = 2048M
extension="redis.so"
extension="imagick.so"

**Laravel Valet 2.11.0**
Can verify valet uses php@7.3
Have verified the server is using php@7.3
https://github.com/laravel/valet/issues/728#issuecomment-462851399 (this was a big pain, and a great find)

Have gone through all the possibilities I can find.

**Comment by trevorpan** [comment]
This one took a few days to pin down. https://laracasts.com/discuss/channels/code-review/maximum-execution-time-of-30-seconds-exceeded-spatie-medialibrary?page=1#reply=621931

Basically, the policy.xml on imagemagick had a setting for pdf which needed read | write permissions. That was part of it, but also on local I use QUEUE_CONNECTION=sync but that was forcing the conversion so I found changing to redis - at least for this attempt - on local really helped as horizon could take the job...

@freekmurze  is it a fair tip on the docs to reference this setting in policy.xml?
```
<policy domain="coder" rights="read | write" pattern="PDF" />
```

**Comment by freekmurze** [comment]
Sure, send a PR for this

**Comment by trevorpan** [comment]
@freekmurze not sure if the fix I suggested made it through? I thought I forked the README and suggested changes with a PR. Did that work? (first time pr'er)
