### ISSUE TITLE
saveImage() generated image with inverted colors

### ISSUE THREAD

**Issue by 4n70w4** [spatie/pdf-to-image#157]
Problem with only this file. Another pdf files generated images without inverted colors. But in another environment images generated without inverted colors (see bellow).

Input PDF:

https://eskvent.ru/upload/iblock/7fd/7fd02aa97e6a18a3ff462e640c993ad0.pdf

![image](https://user-images.githubusercontent.com/38257723/91029643-ac69dd00-e607-11ea-94dd-2fc1e61aeec3.png)

Output jpg:
![image](https://user-images.githubusercontent.com/38257723/91029568-9bb96700-e607-11ea-8acb-27aed660ab27.png)

```php
        $PdfToImage = new Pdf($this->filename);

        $PdfToImage->setOutputFormat('jpg');
        $PdfToImage->setResolution(300);
        $PdfToImage->setCompressionQuality(85);

        $pages = $PdfToImage->getNumberOfPages();

        foreach(range(1, $pages) as $page) {
             $page_file = $this->getFilePath($page);
             $res = $PdfToImage->setPage($page)->saveImage($page_file);
        }
```

```bash
php -v
```

```
PHP 7.4.9 (cli) (built: Aug  4 2020 08:28:13) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies
```

```bash
yum list installed | grep Magick
```

```
ImageMagick.x86_64                        6.9.10.68-3.el7            @base
```

```bash
rpm -q centos-release
```

```
centos-release-7-7.1908.0.el7.centos.x86_64
```

I tried `spatie/pdf-to-image` 1.8.2 and 2.0.1.

But in another environment images generated without inverted colors:

```
PHP 7.4.3 (cli) (built: Feb 18 2020 11:53:05) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
    with Xdebug v2.9.2, Copyright (c) 2002-2020, by Derick Rethans
```

```
centos-release-7-7.1908.0.el7.centos.x86_64
```

```
ImageMagick6-libs.x86_64                  6.9.10.96-1.el7.remi       @remi-safe
```

 `spatie/pdf-to-image` 1.8.2

**Comment by superdejooo** [comment]
Hey @4n70w4 
I had the same problem ...
And I solved it by updating the version of ImageMagick to ImageMagick 7.0.10-28 Q16 x86_64 2020-08-16

Good luck!

**Comment by jvandenrym** [comment]
Have the problem with PDFs that have no explicit background resulting in inverted PDF-to-image generated file.
