### ISSUE TITLE
Imagemagick cannot open file.pdf[0]

### ISSUE THREAD

**Issue by verybigelephants** [spatie/pdf-to-image#16]
what version of the imagemagick do i need? on my server, the code fails on this line 

https://github.com/spatie/pdf-to-image/blob/master/src/Pdf.php#L169
`$imagick->readImage(sprintf('%s[%s]', $this->pdfFile, $this->page - 1));`

saying it can't read a file `...path/to/pdf.pdf[0]` (0 because my pdf has one page)

i am using it in combination with medialibrary

```
ImagickException in Pdf.php line 170:
Failed to read the file
in Pdf.php line 170

at Imagick->readimage('/path_to_project/storage/medialibrary/temp/cO4tPRH3f3POL5X1/A7Vyz9sE2YEQ16AM.pdf[0]') in Pdf.php line 170
at Pdf->getImageData('/path_to_project/storage/medialibrary/temp/cO4tPRH3f3POL5X1/A7Vyz9sE2YEQ16AM.jpg[0]') in Pdf.php line 120

```

i have tried opening a jpg file and it can read the image. the only problem only occurs with pdfs :(

**Comment by freekmurze** [comment]
I have `v 6.9.3-7` installed, but I think this should work with most versions.
