### ISSUE TITLE
getNumberOfPages always return 1. Getting error when i want to setPage(2) or another.

### ISSUE THREAD

**Issue by SargisBeglaryan** [spatie/pdf-to-image#160]
![image](https://user-images.githubusercontent.com/14293395/95875276-e8f1c380-0d82-11eb-9d93-b2f43c579157.png)

https://user-images.githubusercontent.com/14293395/95875276-e8f1c380-0d82-11eb-9d93-b2f43c579157.png

**Comment by freekmurze** [comment]
For my PDFs it works. If the fix is simple, I'd accept a PR that fixes it for you. If possible, also include a test.
