### ISSUE TITLE
PDFDelegateFailed `The system cannot find the file specified. ' @ error/pdf.c/ReadPDFImage/801

### ISSUE THREAD

**Issue by andream1977** [spatie/pdf-to-image#161]
I work on windows 10
I installed
ImageMagick 6.9.3-7 Q16 x64 2016-03-27
and
Ghostscript 9.53.3 for Windows (64 bit)

I set both the paths of these two programs in the windows environment PATH variable

when i go to use the spatie library, i get this error:
PDFDelegateFailed `The system cannot find the specified file. '@ error / pdf.c / ReadPDFImage / 801

this is my code inside phpstorm/laravel:

filename = "test.pdf"
destination_path = "upload".DIRECTORY_SEPARATOR
$path_abs = public_path ($path_destination. $filename);
$pdf = new Pdf (abs_path);

I checked and the pdf file is present in the directory:
C: \ xampp \ htdocs \ myproject \ public \ upload \ test.pdf

can you help me?

**Comment by mduzairmduzair** [comment]
same error

**Comment by mduzairmduzair** [comment]
Error is reloved! just download the oldest version of GhostScript.😍😂
