### ISSUE TITLE
Where is the savedImagePath relative to ?

### ISSUE THREAD

**Issue by boypanjaitan16** [spatie/pdf-to-image#169]
I'm trying to save image like this

```
$pdf    = new Pdf($ebook);
                $pdf
                    ->setPage(1)
                    ->saveImage('storage/public/test.jpg');
```
No error but I can't find the result anywhere. any idea why? Thanks in advance

**Comment by avelia-alessandromarchioro** [comment]
I had the same problem; check your package version, maybe it's a -dev one like mine which is bugged
