### ISSUE TITLE
Lost ability to load PDF via URL

### ISSUE THREAD

**Issue by polygonie** [spatie/pdf-to-image#174]
Starting from version 2.0.0, it's not possible to load a PDF via it's URL (see [changelog](https://github.com/spatie/pdf-to-image/blob/master/CHANGELOG.md#200---2020-01-08)).

My PDF is stored on AWS s3. Before 2.0.0 I could call `$pdf = new Pdf($myUrl);` but now we lost that ability.
I tried with the file path but that didn't work either: `$pdf = new Pdf(Storage::disk('s3')->get($myPathOnS3));`

Is there any work around apart from downgrading to >2.0.0?

**Comment by dominikager** [comment]
i have the same problem
