### ISSUE TITLE
Multiple pages overlapped into one image when pdf is loaded from url

### ISSUE THREAD

**Issue by sagautam5** [spatie/pdf-to-image#180]
I have used url to load a pdf and then converted into images.

    $pdf   = new \Spatie\PdfToImage\Pdf('http://www.africau.edu/images/default/sample.pdf');
    $pages = $pdf->getNumberOfPages();
    
    for ($i = 1; $i <= $pages; $i++) {
        $imageName = $i.'.png';
        $saveImgTo = 'images/' . '/' . $imgName;
        $pdf->setPage($i)->saveImage($saveImgTo);
    }

Image Output:
![1-l1cfvr_sample](https://user-images.githubusercontent.com/10434281/127302806-4b85455d-60fb-497d-9ff0-0281bd1361e2.png)
![2-l1cfvr_sample](https://user-images.githubusercontent.com/10434281/127302810-b4ccb5e3-d5fc-46cd-aaa3-82076e319240.png)

How to Reproduce ?

Version: 1.8.2
PDF Url: [http://www.africau.edu/images/default/sample.pdf](http://www.africau.edu/images/default/sample.pdf)

**Comment by VeyJulien** [comment]
Don't close it mister roboto! I encountered the same issue, and opened a PR #182 which resolves it. Don't really know what caused this unfortunately.

**Comment by Ayrm4x** [comment]
I was able to fix this issue with:

`$pdf->setLayerMethod(null)->saveImage($target);`

**Comment by freekmurze** [comment]
We'll handle this further in #182
