### ISSUE TITLE
"Pdf::setCompressionQuality()"

### ISSUE THREAD

**Issue by emresaracoglu** [spatie/pdf-to-image#195]
Hello,

```
thrown in /var/www/clients/client8/web35/***/vendor/spatie/pdf-to-image/src/Pdf.php on line 108
[10-Apr-2022 20:30:08 Europe/Istanbul] PHP Fatal error:  Uncaught Error: Call to undefined method Spatie\PdfToImage\Pdf::setCompressionQuality()
```

If I use this tag `setCompressionQuality`, I get a 500 error.  What could be the reason for this?

Thank you.

**Comment by lintaba** [comment]
same issue. `setCompressionQuality` got added in 1.6.1, however composer installs version 1.2.2 with php 8.1, as it was >=5.6 for a while, then got changed to `^7.2|^8.0`.

As quick fix you can force the latest version:
```json
"spatie/pdf-to-image": "^2.2",
```

then run:
```bash
composer update --ignore-platform-reqs
```

Also I'm sending a PR to fix the issue.

**Comment by emresaracoglu** [comment]
@lintaba Thank you for your answer and work.
