### ISSUE TITLE
Option to stream image

### ISSUE THREAD

**Issue by joeserg** [spatie/pdf-to-image#2]
Hi there,

I was wondering if we could have the option to stream the image to the browser, rather than saving it to disk?

In my application I would like to show a thumbnail of a dynamically generated PDF, so the image is only relevant for that particular request.

**Comment by freekmurze** [comment]
I'd accept a PR that adds a `getImageData`-function to the package. The function should contain some of the code currently present in `saveImage`. `saveImage` should use the new `getImageData`-function.
