### ISSUE TITLE
getNumberOfPages returns wrong number

### ISSUE THREAD

**Issue by projct1** [spatie/pdf-to-image#200]
I have PDF with 12 pages ![image](https://user-images.githubusercontent.com/9752959/192562142-f56b94a9-67a7-4c69-921d-3cf78a9298f8.png)
But method `getNumberOfPages` returns 48 pages. When i use `saveAllPagesAsImages` i got error:
```
ImagickException
PDFDelegateFailed ` Requested FirstPage is greater than the number of pages in the file: 12 No pages will be processed (FirstPage > LastPage). ' @ error/pdf.c/ReadPDFImage/794
```

**Comment by mgkimsal** [comment]
Is this a zero-index issue?  Is 'page 0' really 'page 1'? @projct1

**Comment by patinthehat** [comment]
@projct1 Can you provide a failing unit test to demonstrate this bug? Thanks!
