### ISSUE TITLE
Image size (width and height) issue

### ISSUE THREAD

**Issue by said15904** [spatie/pdf-to-image#201]
Hi,

I have an issue when I convert a specific pdf file (attached file below)..!

The product images has not the same width and height as the pdf file. 

Thank you for your help
 
![test-0](https://user-images.githubusercontent.com/9935062/200285507-3b744be1-5579-45c9-95fe-48e1eff691fb.png)
[956_1664183805.pdf](https://github.com/spatie/pdf-to-image/files/9950653/956_1664183805.pdf)

**Comment by ntaylor-86** [comment]
I think something is up with that PDF. I tried converting it and get the same result as you.

If I print to PDF using `Microsoft Print to PDF` on windows then try to convert that file the final result looks OK.


Here is the image I get after printing the PDF using `Microsoft Print to PDF`:

![test_2](https://user-images.githubusercontent.com/28693782/215658784-d1d6657f-c653-4085-a1d5-58c81910ed47.jpg)


And here is the PDF:

[test_2.pdf](https://github.com/spatie/pdf-to-image/files/10542506/test_2.pdf)
