### ISSUE TITLE
imagick extintion dose now work

### ISSUE THREAD

**Issue by tarek-attar** [spatie/pdf-to-image#215]
hi there,
i have a project laravel 10 php 8.2 , and i want to use this library spati/pdf-to-image , 
but there is problem , the imagick extention is not work and its important to useing the library , what is the solution??

**Comment by phunq-0851** [comment]
What is your problem? Today, I also installed this package with imagick extension. Its work!
I'm using laravel 10 php 8.2 too

**Comment by ejsinfuego** [comment]
@phunq-0851 what os are you using?

**Comment by phunq-0851** [comment]
@ejsinfuego i'm using WSL2

**Comment by aref79** [comment]
I have this problem too , Can anyone solve this problem?

**Comment by nobel-512** [comment]
> hi there, i have a project laravel 10 php 8.2 , and i want to use this library spati/pdf-to-image , but there is problem , the imagick extention is not work and its important to useing the library , what is the solution??

Same here, Have you found a solution?

**Comment by nobel-512** [comment]
Hi all, I had the same issue.
After many tries and searching everywhere I found that the solution is to use **PHP 8.1.0** instead of PHP 8.2.
Do not worry about Laravel 10 it will work with PHP 8.1.0 too.

**Comment by nobel-512** [comment]
Hi all, I had the same issue.
After many tries and searching in many places, I found that the solution is to use **PHP 8.1.0** instead of PHP 8.2.
Do not worry about Laravel 10 it will work with PHP 8.1.0 too.

**Comment by nobel-512** [comment]
Hi all, I had the same issue.
After many tries and searching in many places, I found that the solution for the **imagick** extention issue, is to use **PHP 8.1.0** instead of PHP 8.2.
Do not worry about Laravel 10 it will work with PHP 8.1.0 too.

**Comment by bobvandevijver** [comment]
If the Imagick extension is the issue, it might be worthwhile to check our fork which no longer relies om Imagick: https://github.com/Drenso/pdf-to-image.

**Comment by patinthehat** [comment]
Closing stale issue - please open a new issue if you're still running into this error. Thanks!
