### ISSUE TITLE
File conversion is really slow...

### ISSUE THREAD

**Issue by santiagazo** [spatie/pdf-to-image#22]
I have been using this package for some time now in our dev enviroment and I love how well it's built, I have struggled how ever with the slowness of the process. I hope it's just my code or something I am doing wrong. We are coming close to launch and I need a faster solution. Would you be willing to look at this and tell me if I am using this code wrong and any thoughts on optimizing it? Currently I am averaging between 2 seconds and as much as 10 seconds per page. So a 30 page document is taking 5 mins to process.

`$files = $request->file('uploadfiles') ?: $request->file('templatefiles');

        if (!file_exists('../storage/app/documents/tmp')) {
            mkdir('../storage/app/documents/tmp', 0777, true);
        }

        foreach($files as $file){
            $title = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
            $description = $request->file('templatefiles') ? 'signable-template' : 'signable-document';
            $fileMime = $file->getClientOriginalExtension();
            $name = str_slug($title);
            $path = '../storage/app/documents/tmp';
            $collection = Auth::id().'-'.str_random(30);

            if($fileMime == 'pdf'){
                // increase timeout on server for really big files.
                ini_set('default_socket_timeout', 900); // 900 Seconds = 15 Minutes
                ini_set('upload_max_filesize', '30M');
                ini_set('post_max_size', '30M');
                ini_set('max_input_time', 900);
                ini_set('max_execution_time', 900);

                $pdf = new Pdf($file->path());
                $totalNumberOfPages = $pdf->getNumberOfPages($file);

                if(isset($totalNumberOfPages)){
                    foreach (range(1, $totalNumberOfPages) as $pageNumber) {
                        $pdfPngName = $name.$pageNumber.'.png';
                        $pdfPngPath = $path.'/'.$pdfPngName;
                        $pdf->setPage($pageNumber, $file)->saveImage($pdfPngPath);
                        $document = $this->documentCreate($name, $pdfPngName, $description, $collection);
                        $documentIdArray[] = ['collection' => $collection, 'document_id' => $document->id, 'name' => $title];
                        $document->addMedia($pdfPngPath)->usingFileName($pdfPngName)->toCollection($collection);
                        File::delete($pdfPngPath);
                    }
                }

            }`

**Comment by sebastiandedeyne** [comment]
I see you're also using our media library package. Are you also doing conversions here?

```
$document->addMedia($pdfPngPath)->usingFileName($pdfPngName)->toCollection($collection);
File::delete($pdfPngPath);
```

If so, you could throw these on a queue so they get processed asynchronously while you can iterate over the other pages.
