### ISSUE TITLE
 " Class 'Imagick' not found"  how to solve

### ISSUE THREAD

**Issue by new123-ui** [spatie/pdf-to-image#224]
[0] ThrowableError in Pdf.php line 164     , Class 'Imagick' not found

**Comment by Erol314** [comment]
install imagick extension.
Further may vary depending of your OS, etc.

In my case I use ppa:ondrej/php for multiple php versions under Ubuntu 22.04 and the command was  
`sudo apt-get install php8.2-imagick`

**Comment by new123-ui** [comment]
Thank you for your help

**Comment by patinthehat** [comment]
Thanks for your help!
