### ISSUE TITLE
Catch ImagickException

### ISSUE THREAD

**Issue by hellohereiam** [spatie/pdf-to-image#23]
Thank you for this class, very useful! As I using this class for generating thumbnails from user provided PDFs it turns out that every once in a while ImagickException throws an exception. As the conversion with ImagickException has no try/catch this exception is not catched and is also not catchable from outside the class, as its already terminating the process within the class. 
More precisely this happens for me every once in a while in getImageData() when $imagick->readImage() is called. Would it be feasible to introduce a try/catch there, so one could catch the error from outside the class and handle it appropriately? 

Thanks so much!

**Comment by sebastiandedeyne** [comment]
Why can't you catch the Imagick exception when calling this code?

**Comment by hellohereiam** [comment]
Thanks, I am at a loss what I was doing when I reported this – as far as I can tell I have figured it out and it was a misunderstanding from my end. Sorry for the trouble.
As far as I can see I can catch any ImagickException from outside the class, so not a problem on the classes end.

``
try {
           //do anything that might involve potential imagick errors
        } catch (\ImagickException $exception) {
            //imagemagick error
        }
``

Thanks.

**Comment by sebastiandedeyne** [comment]
Cool, nice to hear this was resolved :)
