### ISSUE TITLE
Converting fails on window

### ISSUE THREAD

**Issue by gazmend-sahiti** [spatie/pdf-to-image#232]
I recently tried to use this package on a windows environment and had to rename the "gswin64" to gs as a quick solution to make it work. 

The package always uses the command "gs", on Windows the Ghostscript exe is not called gs it might be:
gswin32, gswin32c, gswin64 or gswin64.

**Comment by patinthehat** [comment]
Imagemagick specifies the `gs` binary name under the hood, not the package directly. We'd be happy to review a PR that allows modification of the ghostscript binary name, though. Thanks! :+1:
