### ISSUE TITLE
Form loses font format

### ISSUE THREAD

**Issue by psjavi** [spatie/pdf-to-image#233]
I've got a pdf with a form and custom fonts and colors.

When I convert the file to jpg or png, the form is losing the format.

What's wrong?

**Comment by patinthehat** [comment]
@psjavi Could you elaborate a bit? 
- Is it not carrying over the fonts, the colors, or both? 
- Is this within the form, or throughout the document? 
- Is it just when converting to jpg or png, or also webp? 
 
Thanks for reporting the issue! :+1:

**Comment by tomfriwel** [comment]
> Hi,
> 
> I discovered that is a problem with imagick command directly. I've had to change the package and use directly pdftoppm instead of imagick.

`pdftoppm` works. If there is garble in the text, use `fc-list :lang=xxx` to check that the system has installed the corresponding font.
