### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by DarknesChaos** [spatie/pdf-to-image#25]
When I try to convert a file shows the class message 'Imagick' is not found, try installing the class but the message persists. Any idea why that happens.

this it's my code:

$file_logo=Input::file('image');

            $folder = public_path().'/images/magazine';
            if(!file_exists($folder)){
                mkdir($folder, 0777, true);
                $pdf = new \Spatie\PdfToImage\Pdf($file_logo);
                foreach (range(1, $pdf->getNumberOfPages()) as $pageNumber) {
                    $pdf->setPage($pageNumber)->saveImage($folder.'/'.'page'.$pageNumber.'jpg');
                    $magazine = new Magazine;
                    $magazine->img_magazine = 'images/magazine/'.'page'.$pageNumber.'jpg';
                    $magazine->save();
                }
            }else{
                $pdf = new \Spatie\PdfToImage\Pdf($file_logo);
                foreach (range(1, $pdf->getNumberOfPages()) as $pageNumber) {
                    $pdf->setPage($pageNumber)->saveImage($folder.'/'.'page'.$pageNumber.'jpg');
                    $magazine = new Magazine;
                    $magazine->img_magazine = 'images/magazine/'.'page'.$pageNumber.'jpg';
                    $magazine->save();
                }
            }

**Comment by freekmurze** [comment]
Probably you haven't installed `Imagick` correctly.

Run `phpinfo();` inside a web request and `php -i` on the commandline. Output of both should mention that `Imagick` is installed.

**Comment by DarknesChaos** [comment]
I run phpinfo (); Inside a web application and php -i at the command line. Output of both if you mention that Imagick is installed. But still the same error. I don't know what's wrong

**Comment by noveweb** [comment]
Any solution?
