### ISSUE TITLE
Composer run error imagic, but its already installed on my environment

### ISSUE THREAD

**Issue by muhammad-ihsan** [spatie/pdf-to-image#28]
hi there, i tried to install this packages in my project then return this error:
```
Problem 1
    - Installation request for spatie/pdf-to-image ^1.3 -> satisfiable by spatie/pdf-to-image[1.3.0].
    - spatie/pdf-to-image 1.3.0 requires ext-imagick * -> the requested PHP extension imagick is missing from your system.
```
I have enable the imagick extension in my environtment

**Comment by maxi032** [comment]
I have the same problem. I am using wamp and php7.1 I have imagemagick 3.4.3 installed

**Comment by arifmasood** [comment]
@muhammad-ihsan @maxi032 were you able to solve this issue ?

**Comment by nappalm** [comment]
how to solved?

**Comment by OAmor** [comment]
why this issue is closed without solution ??
