### ISSUE TITLE
Failed to Execute Command

### ISSUE THREAD

**Issue by muhammad-ihsan** [spatie/pdf-to-image#29]
why i getting this error? PHP 5.6.10
```
"" on line 29 of /Users/ihsan/Projects/sahabatjadisah/plugins/barndev/wedding/vendor/spatie/pdf-to-image/src/Pdf.php
```

**Comment by freekmurze** [comment]
The file that you are passing to the Pdf class probably does not exist.

https://github.com/spatie/pdf-to-image/blob/master/src/Pdf.php#L29
