### ISSUE TITLE
Hypothesis: use filesystem abstraction

### ISSUE THREAD

**Issue by lucasaba** [spatie/pdf-to-image#31]
Just a thought: do you think it would be interesting to extend pdf-to-image to support filesystem abstraction ?

I'm using pdf-to-image in my app and I'm circuventing things so that I can use Gaufrette to access my files. I was thinking to create a new "extension" to pdf-image but, if you think it could be usefull to others I can also try to add new methods to Pdf.php so that it can use Gaufrette....

What do you think ?

**Comment by freekmurze** [comment]
Hi, thanks for your suggestion. 

I'd like to keep this package very simple, so probably won't accept a PR that adds filesystem abstraction.
