### ISSUE TITLE
Bad quality of images

### ISSUE THREAD

**Issue by ryakoviv** [spatie/pdf-to-image#36]
Thanks for simple and awesome package. 
I've found an issue.
All images which were generated from PDF have bad quality. I've tried to change resolution, but it changed nothing. So I've researched your code and I've found resolution does not working in your package. To provide resolution you need to set value of resolution  before of reading PDF file. You can find a lot of examles one of them [here ](http://stackoverflow.com/questions/15237994/convert-pdf-to-high-quality-jpg-using-php-and-imagemagick). So problem is you read PDF file in __construct and then set resolution in getImageData (you try to read again after changing resolution in getImageData but actually it does not work)
My suggestions
PDF file must be read in __construct because method getNumberOfPages works based on this. I suggest to change your getImageData method like this:
```
public function getImageData($pathToImage)
    {
        $imagick = new \Imagick();
        $imagick->setResolution($this->resolution, $this->resolution);

        $imagick->readImage(sprintf('%s[%s]', $this->pdfFile, $this->page - 1));

        $imagick->mergeImageLayers(\Imagick::LAYERMETHOD_FLATTEN);

        $imagick->setFormat($this->determineOutputFormat($pathToImage));

        return $imagick;
    }
```
you can try by yourself and maybe find better solution.  Thanks again for great package

**Comment by freekmurze** [comment]
Hi, 

thanks for investigating this. I'd accept a non breaking PR that fixes this.
