### ISSUE TITLE
size of PDF page and image are different

### ISSUE THREAD

**Issue by ryakoviv** [spatie/pdf-to-image#37]
How to get an image with the same size (width and height) as the according pdf page?

**Comment by lasseal** [comment]
This is likely caused by the (read) resolution for Imagick (PHP lib used by this package) being set differently than the PDF being converted. It would be great if one could publish a config file and change the resolution one self. Changing the resolution variable in the vendor files directly won't even work. See PR #58.

**Comment by pliasun** [comment]
Does not work setting resolution.
```
            $pdf = new \Spatie\PdfToImage\Pdf($on_server.$filename_pdf);
            $pdf->setResolution(300);
            $pdf->setOutputFormat('png')->saveImage($on_server.$temp_filename);
```
File input 
[AmicMapPin.pdf](https://github.com/spatie/pdf-to-image/files/1153715/AmicMapPin.pdf)

File output only 63x63 pixels
![64a459c99b8aaa26b527be0622303a7e](https://user-images.githubusercontent.com/26012205/28285383-2d11ab52-6b3d-11e7-869b-b1500c89a305.png)

**Comment by nitinjiniguru** [comment]
not work for me

**Comment by pliasun** [comment]
@nitinjiniguru yes, i am comment this code
``  //$this->imagick->mergeImageLayers(\Imagick::LAYERMETHOD_FLATTEN); ``
in \vendor\spatie\pdf-to-image\src\Pdf.php
in function getImageData($pathToImage)
![image](https://user-images.githubusercontent.com/26012205/29807367-50c9867a-8c9c-11e7-8339-425de38704ea.png)

and my full code
![image](https://user-images.githubusercontent.com/26012205/29807386-62d62e86-8c9c-11e7-98c7-6ed5e301c9b4.png)

**Comment by nitinjiniguru** [comment]
Thanks @pliasun  its work for me..

i found the place where to solve the issue and i change according i require
