### ISSUE TITLE
getNumberOfPages()

### ISSUE THREAD

**Issue by santiagazo** [spatie/pdf-to-image#5]
I am posting this here for spatie... and for anyone else that is running into this issue. I have been trying to work with the getNumberOfPages() function and unfortunately on our server (centos) this function has returned 0 without fail. Imagick is installed correctly but fails to respond correctly. As far as I can tell there is no bug in the spatie/pdf-to-image repository... the code here is immaculate (thank you spatie).

So if you've found the same issue I found this code to work very well. 

            $pdfcontent = file_get_contents($filePath, NULL, NULL, 0, 300);
            preg_match("~Linearized.*?\/N ([0-9]+)~s", $pdfcontent, $pages);
            if(isset($pages[1])){
                echo "Pages ".$pages[1];
            }

Spatie, if you would like to make some type of fallback system or change your getNumberOfPages() function I have found this to work very well...AND RIDICULOUSLY FAST.

**Comment by freekmurze** [comment]
Thanks for posting this. We're currently using Ubuntu and it seems to work fine. If there are more people reporting this problem, I'll keep your fix in mind.

**Comment by robgoodliffe** [comment]
I was also struggling to get the page count on my local laravel homestead box. 

I extended the class if number of pages returned as 0.

```php
    public function fixCountNumberOfPage(){
        $image = new Imagick();
        $image->pingImage($this->pdfFile);
        $this->numberOfPages = $image->getNumberImages();
    }
```

No idea why this would work and the current solution doesn't.

Hope this can help somebody else.

**Comment by voicecode-bv** [comment]
@robgoodliffe Thanks for this! I'm having the same issue using Laravel Valet. Your code actually returns the correct number of pages in the document. Still, when I want to save all pages, the PDF class will automatically fall back on the build in getNumberOfPages() method, which returns 0 again. How did you prevent this from happening?
