### ISSUE TITLE
PDF will not load with version ^1.4.2 & master

### ISSUE THREAD

**Issue by deonthomasgy** [spatie/pdf-to-image#60]
$this->imagick = new \Imagick(); 

^^ nothing assigned to Imagick(????);

**Comment by Immortal-Pain** [comment]
Maybe you don't have Imagick installed?

**Comment by deonthomasgy** [comment]
I do have it installed, i battled with Imagick for hours just to find out that pdf-to-image does NOT pass the pdfFile onto Imagick, it was very frustrated as a colleague of mine with the same project was working fine and mine was not. After some digging, i found out that the version he was using was 1.4.1, i was using @dev, only major difference is 

Previous version
`$this->imagick = new \Imagick($pdfFile);`

Newer Version
`$this->imagick = new \Imagick();` //BROKEN

MY PHP Server (includes Imagick 3.4.3): https://github.com/deonthomasgy/docker-php-fpm

**Comment by freekmurze** [comment]
@deonthomasgy there was indeed a bug in version 1.4.2. 

I've tagged a new version 1.4.3 where this has been fixed.

Run `composer update` to pull in that fix.

If the problem persists, please reopen this issue.
