### ISSUE TITLE
i tried to install this packages in my project on mac then return this error:

### ISSUE THREAD

**Issue by dwilanang** [spatie/pdf-to-image#65]
Problem 1
- spatie/pdf-to-image 1.4.5 requires ext-imagick * -> the requested PHP extension imagick is missing from your system.

**Comment by fgilio** [comment]
This actually has nothing to do with the package itself. It needs ImageMagick to work, and you need to have it installed.
Don't know which version of PHP you use, but this might come helpful: https://www.google.com.ar/search?q=brew+install+php+imagick&oq=brew+install+php+ima&aqs=chrome.3.69i57j0l4j69i64.5071j0j7&sourceid=chrome&ie=UTF-8
For example for php 7: brew install php70-imagick

**Comment by dwilanang** [comment]
thanks for your help
