### ISSUE TITLE
Solution for error with Imagick and Ghostscript x64 in Windows

### ISSUE THREAD

**Issue by sdkcarlos** [spatie/pdf-to-image#66]
I've installed Ghostscript in Windows to work with the library, however I was getting the following message:

```
PDFDelegateFailed `The system cannot find the file specified. ' @ error/pdf.c/ReadPDFImage/801
```
 I installed Ghostscript 9.21 for 64 bits in my Windows machine, so the executables of ghostscript are (`gswin64.exe` etc). That's why I looked the source code of the library to see if I could change someway the executable path, however **the problem was someway in Imagick and that's nothing that you can simply change in some file**. The issue here is that I'm using Xampp and it has installed Imagick x86 (32 bits), so installing Ghostscript for 32 bits solved the problem.

By itself, this is not an issue for the library but between imagick and Ghostscript, I am publishing this just in case that someone faces the same error and may need a light to solve it. Useful wrapper btw, thanks !

**Comment by freekmurze** [comment]
Thanks for posting your solution.

**Comment by Bhavin9898** [comment]
@sdkcarlos 

Thanks for the solution.

Can you tell me that we can not setup with 64 bit?

**Comment by TuanVnit** [comment]
@dev-panpic I have same you solution. Could you help fix it.
My fail: : 
"PDFDelegateFailed `The system cannot find the file specified.\r\n' @ error/pdf.c/ReadPDFImage/810"
I use ghostSscrip 9.25

**Comment by jaikant19** [comment]
ImagickException #415
FailedToExecuteCommand `"gs" -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r72x72" -dPrinted=false "-sOutputFile=C:/Users/Dell/AppData/Local/Temp/magick-ShnbzUrI_n4yC4rub7N7mfxwMQfJFEz3%d" "-fC:/Users/Dell/AppData/Local/Temp/magick-lSYfX-99IFjhE_7yndrAkmXEVRT5ejvj" "-fC:/Users/Dell/AppData/Local/Temp/magick-1bxqjBtBCI45IypQK-x0ASGtNCmJRId2"' (The system cannot find the file specified.
) @ error/delegate.c/ExternalDelegateCommand/516
