### ISSUE TITLE
Failed to read file error

### ISSUE THREAD

**Issue by scrwdnet** [spatie/pdf-to-image#68]
When converting a PDF (via Media Library Conversion) I get the error 'Failed to read file':

```
"message": "Failed to read the file",
"file": "/Users/samjones/Desktop/DEVELOPMENT/Safe/system/vendor/spatie/pdf-to-image/src/Pdf.php",
"line": 40,
"trace": [
    {
        "file": "/Users/samjones/Desktop/DEVELOPMENT/Safe/system/vendor/spatie/pdf-to-image/src/Pdf.php",
        "line": 40,
        "function": "__construct",
        "class": "Imagick",
        "type": "->",
        "args": [                   
"/Users/samjones/Desktop/DEVELOPMENT/Safe/system/storage/medialibrary/temp/Vrc0otFnhMccJQ61BaGu96DUtVk1cwJs/c0ZJJdOuTNlTDeyZ.pdf"
        ]
    },
    ...
]
```

File is there and permissions seem ok, PHP 7.1 and latest ImageMagick 7.0.7-0.

Any ideas? 

UPDATE: after restarting the server and reinstalling ImageMagick I'm now getting an error with GhostScript (which presumable ImageMagick is delegating the conversion to.

`FailedToExecuteCommand 'gs' -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=pngalpha' -dTextAlphaBits=4 -dGraphicsAlphaBits=4 '-r72x72'  '-sOutputFile=/var/tmp/magick-266Xh1FBuVfcugv%d' '-f/var/tmp/magick-266OVALiKuMKxoy' '-f/var/tmp/magick-266dsJDEkjrkKzd'' (1) @ error/pdf.c/InvokePDFDelegate/291` 

GhostScript is installed and working on the command line but it seems ImageMagick is struggling with it?!

**Comment by joshuadegier** [comment]
Might be the same issue as I faced this afternoon. Are you testing this locally on your mac? If so, it's possible that apache can't access the ghostscript path. It's located in `/usr/local/bin/gs` and it should be symlinked to `/usr/bin/gs` by running this command: `sudo ln -s /usr/local/bin/gs /usr/bin/gs`.

If you face any permission errors while creating the symlink, please follow the steps as mentioned in this question on Stackoverflow: https://stackoverflow.com/questions/37927247/imagick-dont-open-pdf-files-with-failed-to-read-the-file-exception

Please let us know if this fixed your issue.

**Comment by scrwdnet** [comment]
Holy shit. I love you.

Can't believe I hadn't seen this SO question (after hours of pulling my hair out). Had to do the funky recovery mode stuff but it worked first time after adding in that symlink.

Might be worth a foot note in the readme, seems like it could be a pain point for certain Mac users? Both iMagick and GhostScript were installed via HomeBrew so could be the issue? ¯\\\_(ツ)_/¯

You sir are on my 'owe you a beer' list.

**Comment by joshuadegier** [comment]
Great to had, glad I could be of any help. Enjoy working on your application and I'll make sure I don't forget about that beer ;-)

**Comment by penrcz** [comment]
Thank you joshuadegier .

**Comment by kennj2016** [comment]
@joshuadegier ,  I have the same issue, i use window

**Comment by joshuadegier** [comment]
Sorry @kennj2016, I'm not working with Windows

**Comment by 58bits** [comment]
I also owe you a beer. Thanks - `sudo ln -s /usr/local/bin/gs /usr/bin/gs` worked for us too.

**Comment by vimalmistry** [comment]
Hi, I am facing this same issue. But I am using nginx with php fpm. I tried 
`sudo ln -s /usr/local/bin/gs /usr/bin/gs`
But not working

**Comment by cicsolutions** [comment]
Sorry to piggyback on an older post, but this looks like the place to present my question.  I too am getting the FailedToExecuteCommand 'gs' error.  I installed imagemagic and ghostscript with Homebrew, and when I check the path to gs with `which gs`, I receive `/usr/local/bin/gs`.  

I'm on a mac, not familiar with FMP (don't think I'm using it), and in my .bash_profile file, I've added `/usr/local/bin:/usr/bin:/bin` to my export PATH.  

When I try to run the above suggested symlink `sudo ln -s /usr/local/bin/gs /usr/bin/gs`, I am receiving the following message `ln: /usr/bin/gs: Operation not permitted`

I'm really not very educated on all of this ... can anyone point me in the right direction?  Thanks so much!

**Comment by joshuadegier** [comment]
You might want to follow this: https://stackoverflow.com/questions/32659348/operation-not-permitted-when-on-root-el-capitan-rootless-disabled

Don't forget to re-enable csrutil afterwards if it fixed your problem.

**Comment by cicsolutions** [comment]
Thank you so much @joshuadegier.  I see in the thread you shared that I can disable csrutil, make the symlink and then re-enable csrutil, however there is another answer on the thread that says a better solution is to install in the `/usr/local/bin` directory rather than the `/usr/bin` directory.  It seems hombrew has already done this, so shouldn't there be a way to reference ghostscript in the `/usr/local/bin` directory that doesn't require symlinking the files to `/usr/bin`?  I would have thought placing `/usr/local/bin/gs` in my bash_profile export PATH is the way to tell my system where to look for ghostscript.

I'm just trying to understand things better, but perhaps having the files located in /usr/bin is what the spatie-pdf package requires?  Just thought I'd ask before trying the csrutil disable/symlink/enable approach.  Thank you so much for your help.

**Comment by joshuadegier** [comment]
I have honestly no idea wether or not Spatie's package relies on ghostscript being in `/usr/bin/gs`. If it wasn't I suppose it should also work without a symlink being created at all..

**Comment by youngbobby** [comment]
If you're using Laravel Herd, the php-fpm.conf file you're looking for should be located here: `~/Library/Application\ Support/Herd/config/fpm`

Basically:

`cd ~/Library/Application\ Support/Herd/config/fpm`

and then (in my case)

`nano 8.2-fpm.conf`

and then add to the end of the line: 

`env[PATH] = /usr/local/bin:/usr/bin:/bin`

If you're using Homebrew, the env path would probably be: 

`env[PATH] = /opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin`

**Comment by davidlapham** [comment]
@youngbobby thanks for that! I was trying to get it to work with Herd. Still having issues on production though (using Forge)

**Comment by AndreKelling** [comment]
There is not much to find on the internet about that issue with `error/pdf.c/InvokePDFDelegate/291`.

On my side PATH stuff and `gs` was fine.

My hosting support needed to change something with an **AppArmor-Security Policy** on server.
