### ISSUE TITLE
Unable to load

### ISSUE THREAD

**Issue by swarajmaniyar** [spatie/pdf-to-image#70]
**I ran below command on my Ubuntu 16.04 

ABC:~$ composer require spatie/pdf-to-image**

**& following was shown:**

PHP Warning:  Module 'imagick' already loaded in Unknown on line 0
Using version ^1.4 for spatie/pdf-to-image
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files

**Now when I wrote following code:**

<?php
	$pdf = new Spatie\PdfToImage\Pdf('Local.pdf');
	$pdf->saveImage('TEST.png');
?>

**I got following error:**

PHP Fatal error:  Uncaught Error: Class 'Spatie' not found in /var/www/html/ABC/ABC.php:16
Stack trace:
#0 {main}
  thrown in /var/www/html/abc/TEST.php on line 16

Can You please tell me what is exactly is written wrong.

**Note:** I have Imagick & Ghostscript installed already. When I used following code:

	$image = new Imagick( 'Local.pdf');
	$image->setImageFormat( "png" );
	$image->writeImage('TEST.png');

It created output. I was thinking of using spatie after visiting this site: https://murze.be/2015/07/convert-a-pdf-to-an-image-using-php/ 
So please let me know what needs to be done to get correct output.

**Comment by introwit** [comment]
Hi :) Create the instance of the Pdf class using the full namespace as shown [here](https://github.com/spatie/pdf-to-image#usage)
