### ISSUE TITLE
No Decode Delegate For This Image Format

### ISSUE THREAD

**Issue by FlameadoDeMoe** [spatie/pdf-to-image#80]
Hi, I'm using this library to convert a PDF file to PNG image but when I execute my PHP code I get this error: 

"Uncaught exception: NoDecodeDelegateForThisImageFormat `PDF' @ error/constitute.c/ReadImage/501"
<p>Throwed in PathToLibrary\Pdf.php:42</p>

PDF line 42 is: `$this->imagick = new Imagick($pdfFile);` in the construct of the class.

I've tried with some pdfs, and I get the same error with all of them. They only have text.

Thanks for your attention.

**Comment by loranger** [comment]
For a reason I can't figure out, it seems the latest imagemagick version bundled for [homebrew](https://brew.sh/) does not embed the pdf delegate anymore :

```bash
convert -version
Version: ImageMagick 7.0.7-11 Q16 x86_64 2017-11-12 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png tiff xml zlib
```

The exception may comes from this lack of delegate

**Comment by mahone2080** [comment]
I also met this problem on windows.Imagick cannot delegate ghostscript.But I'm not fixed yet.

**Comment by raana96** [comment]
I have the same problem, thank you for your help. 
I searched a lot but did not find the right answer! I did not install **Imagick **and **ghostscript** properly, but I do not think I did a small job!
I placed C:\ghostscript\bin in my PATH variable in Windows, but still I have got Uncaught exception 'ImagickException' with message NoDecodeDelegateForThisImageFormat when I call readImageFile !

I can do the conversion using `convert test.pdf test.jpg` command in Windows CMD, but I get this error with the php code:

> Fatal error: Uncaught ImagickException: NoDecodeDelegateForThisImageFormat `PDF' @ error/constitute.c/ReadImage/509 in C:\xampp\htdocs\project\vendor\spatie\pdf-to-image\src\Pdf.php:40 Stack trace: #0 C:\xampp\htdocs\project\vendor\spatie\pdf-to-image\src\Pdf.php(40): Imagick->pingimage('C:/xampp/htd...') #1 C:\xampp\htdocs\project\pdfToImaage.php(7): Spatie\PdfToImage\Pdf->__construct('C:/xamp/htd...') #2 {main} thrown in C:\xampp\htdocs\project\vendor\spatie\pdf-to-image\src\Pdf.php on line 40

**Comment by nndproject** [comment]
`Version: ImageMagick 7.0.11-4 Q16 x86_64 2021-03-20 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules
Delegates (built-in): bzlib djvu fftw fontconfig freetype heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png tiff webp wmf xml zlib
`

same issue in version 7.0.11-4 OS Debian AWS

**Comment by christoph-werker** [comment]
This solution works for me. 
https://stackoverflow.com/questions/52861946/imagemagick-not-authorized-to-convert-pdf-to-an-image
