### ISSUE TITLE
required arguments out of constructor

### ISSUE THREAD

**Issue by peyman-mohamadpour** [spatie/pdf-to-image#81]
Could you please revise the way this useful object is instantiated?

You could consider some more flexible alternative way:

```php
$spatiePdf = new Spatie\PdfToImage\Pdf();
$spatiePdf->setPdf('filePdf');
...
```
This way, your object can easily be registered as a service, thus could be injected inside other application dependencies.

It would be appreciated if you consider this ...

**Comment by freekmurze** [comment]
I'm going to leave things as they are for now.
