### ISSUE TITLE
file_put_contents failed to open stream: Permission denied

### ISSUE THREAD

**Issue by Tex-wz** [spatie/pdf-to-image#82]
Here my code!
```
$pdf = new Spatie\PdfToImage\Pdf($_SERVER['DOCUMENT_ROOT'] ."/ocr/aa.pdf");

$pdf->saveImage(__DIR__."/uploadz");
````

The error message
`Warning: file_put_contents(C:\Xampp\htdocs\ocr/uploadz): failed to open stream: Permission denied in C:\Xampp\htdocs\ocr\vendor\spatie\pdf-to-image\src\Pdf.php on line 164`

**Comment by freekmurze** [comment]
I'm guessing it has something to do with how permissions are set up on your machine.

You could also try using `\` instead of `/`.
