### ISSUE TITLE
Too many pages

### ISSUE THREAD

**Issue by Pixelairport** [spatie/pdf-to-image#83]
Hi. I wasted the whole day to find a solution, but only got a bit closer to it... i hope. I transform pdfs to images. If the pdfs have not so much pages it works. But i try it with a pdf with 44 pages for example and got this error and nothing will happen...

@ error/delegate.c/ExternalDelegateCommand/463

After testing the whole day my last step forward was:
When I replace ...

```
$this->imagick = new Imagick($pdfFile);
```
to 
```
$this->imagick = new Imagick($pdfFile.'[0]');
```

... first page is rendered. If I change the 0 to 1, 2, or something else everytime the first page is rendered. Hope somebody can help...

**Comment by orlyapps** [comment]
Same problem here. Pdf with over 400 pages. 
Workaround for medialibrary use:

1. Change config/medialibrary.php
"Spatie\MediaLibrary\ImageGenerators\FileTypes\Pdf::class" to "\App\Overrides\FileTypePdf::class"
```
    'image_generators' => [
        Spatie\MediaLibrary\ImageGenerators\FileTypes\Image::class,
        \App\Overrides\FileTypePdf::class,
        Spatie\MediaLibrary\ImageGenerators\FileTypes\Svg::class,
        Spatie\MediaLibrary\ImageGenerators\FileTypes\Video::class,
    ],
```

2. Create \App\Overrides\FileTypePdf
```
class FileTypePdf extends \Spatie\MediaLibrary\ImageGenerators\FileTypes\Pdf
{
    public function convert(string $file, Conversion $conversion = null): string
    {
        $imageFile = pathinfo($file, PATHINFO_DIRNAME).'/'.pathinfo($file, PATHINFO_FILENAME).'.jpg';
        (new PdfToImage($file))->saveImage($imageFile);
        return $imageFile;
    }
}
```

3. Create \App\Overrides\FileTypePdf
```
class PdfToImage extends \Spatie\PdfToImage\Pdf
{
    public function __construct($pdfFile)
    {
        if (! filter_var($pdfFile, FILTER_VALIDATE_URL) && ! file_exists($pdfFile)) {
            throw new PdfDoesNotExist();
        }

        $this->imagick = new Imagick($pdfFile.'[0]');
        
        $this->numberOfPages = $this->imagick->getNumberImages();

        $this->pdfFile = $pdfFile;
    }
}
```
