### ISSUE TITLE
Creating image with white area around

### ISSUE THREAD

**Issue by mkurricz** [spatie/pdf-to-image#86]
Hi,
I am getting mostly what I want but some files are generating images with white areas around image with no particular reason (same settings, PDFs have no white borders or something).
I have attached image that I get and original PDF.

Please if you can help me how to handle this kind of bugs would be cool.
Thanks a lot.

[planeo.pdf](https://github.com/spatie/pdf-to-image/files/1699543/planeo.pdf)
![cs9zieuaxeatwiinm3thwvra](https://user-images.githubusercontent.com/35524304/35866417-6ea2965c-0b57-11e8-89e3-5f7ce29191b0.jpg)

**Comment by supriyakhankar** [comment]
I am getting same issue. Please help. Its urgent

**Comment by freekmurze** [comment]
I guess this has something to do with the particular PDF you're converting, I'm not getting this with the pdf's I try.

I'd accept a PR if there's something that can be fixed in this package.
