### ISSUE TITLE
Multiple Page to One Image

### ISSUE THREAD

**Issue by pararang** [spatie/pdf-to-image#87]
Halo,

I have to convert a transaction history that printed in two page pdf file. But when I convert it to jpg format, only the 1st page that converted to the image.

**Comment by freekmurze** [comment]
Without you showing any of your code it's hard to debug this issue.

Please take a look at our readme so see how you can detect the amount of pages and how you can create an image per page.

**Comment by yejing2017** [comment]
remote pdf url +1

**Comment by dawiddczaja** [comment]
I have the same problem, my pdf has 65 pages and in one image is printed all pages 

My code:

`$pdf = new Spatie\PdfToImage\Pdf($pdfUrl); `
`$pdf->saveAllPagesAsImages('images');`

There is any solution for that ?

**Comment by mohsinalandsterling** [comment]
I'm facing the same issue, this code was working fine but now it's only converting the first page into an image.

```
 if (\request()->hasFile('file') && \request()->file('file')->isValid()){

            $pdf_name = time().'.pdf';

            \request()->file->storeAs('pdf-docs',$pdf_name);

            if (file_exists(storage_path('app/pdf-docs').'/'.$pdf_name)){

                $pdf = new Pdf(storage_path('app/pdf-docs').'/'.$pdf_name);

                $pages = $pdf->getNumberOfPages();

//                dd($pages);  // this always gives 1

                for ($i = 1; $i <= $pages; $i++){

                    $filename = storage_path('temp/'.time().'pdf-docs.jpg');

                    $pdf->setPage($i)->saveImage($filename);

                    $resource->addMedia($filename)->toMediaCollection($collection);
                }

            }
}
```

**Comment by mtuchi** [comment]
>  $pages = $pdf->getNumberOfPages();
> 
> // dd($pages);  // this always gives 1

I had the same problem only to realize the version I was outdate and on the `getNumberOfPages` function it was hardcoded to return 1 only. So I installed a specific version. Try version 2.0.1

> composer require spatie/pdf-to-image:2.0.1

Make sure you have PHP extension for Imagick

**Comment by karthikeyanganesandev** [comment]
change the saveAllPagesAsImage like below

 public function saveAllPagesAsImages(string $pathToImage, string $file_name = ''): string
    {
        $numberOfPages = $this->getNumberOfPages();
        $data = ""; 
        if ($numberOfPages >  0) { 
            $img = new Imagick();
        for( $i = 1; $i <= $numberOfPages; $i++  )
        {  
             $this->setPage($i);
             $img_path = $pathToImage.DIRECTORY_SEPARATOR.explode(".",$file_name)[0].$this->page.'.'.$this->outputFormat; 
             $im_dt = $this->getImageData($img_path);
             $img->addImage($im_dt);  
        }   
        $img->resetIterator(); 
        $combined = $img->appendImages(true);
        $img->destroy();
        $combined->writeImage($pathToImage.DIRECTORY_SEPARATOR.$file_name);
        $combined->destroy();
         return $pathToImage.DIRECTORY_SEPARATOR.$file_name;
        } 
    }

**Comment by aponscat** [comment]
You can subclass the Pdf to a class MyPdf and create a new funcion, like this.

<?php

namespace App\Console\Commands;

use Spatie\PdfToImage\Pdf;

class MyPdf extends Pdf {
    public function saveAllPagesAsImages(string $pathToImage, string $file_name = ''): string {
        $numberOfPages = $this->pageCount();
        $data = "";
        if ($numberOfPages > 0) {
            $img = new \Imagick();
            for( $i = 1; $i <= $numberOfPages; $i++ ) {
                $this->selectPage($i);
                $img_path=$pathToImage."$i".'_'.$file_name;
                $this->save($img_path);
                //$img_path = $pathToImage.DIRECTORY_SEPARATOR.explode(".",$file_name)[0].$i.'.'.$this->outputFormat->value;
                $im_dt = $this->getImageData($img_path, $i);
                $img->addImage($im_dt);
            }
            $img->resetIterator();
            $combined = $img->appendImages(true);
            $img->destroy();
            $combined->writeImage($pathToImage.DIRECTORY_SEPARATOR.$file_name);
            $combined->destroy();
            return $pathToImage.DIRECTORY_SEPARATOR.$file_name;
        }
    }
}

Then call it like:
            $pdfPath = $file->getPathname();
            $outputBaseName = pathinfo($file->getFilename(), PATHINFO_FILENAME);
            $outputDir = $folder . DIRECTORY_SEPARATOR . 'images';

            $pdf = new MyPdf($pdfPath);
            $outputPath = $outputDir . DIRECTORY_SEPARATOR;

            $res=$pdf
            ->quality(90)
            ->backgroundColor('white')
            ->layerMethod(LayerMethod::Merge)
            ->saveAllPagesAsImages($outputPath, "$outputBaseName.jpg");
