### ISSUE TITLE
Add access to appendImages()

### ISSUE THREAD

**Issue by abarta** [spatie/pdf-to-image#89]
Hi there,

Firstly, thank you for writing this package.

Recently, I needed to append multiple files from a PDF into one JPG file and could not. I could not  access the appendImages() method of imagick.php class from your class as $imagick property is protected.

I suggest adding a new method that allows setting $this->imagick->appendImages(true) if needed.

Thanks!

**Comment by freekmurze** [comment]
I've gone ahead and made `$imagick` public so you can do whatever you want.
