### ISSUE TITLE
PHP out of memory and killing PHP process

### ISSUE THREAD

**Issue by adilsaeed31** [spatie/pdf-to-image#9]
Hi,
I'm using your library to process PDF files through Dropbox API in Laravel 5 queues with supervisor, It's working very slow and consuming lots of memory to process the PDF image file into JPG image. anyway that's not the actual problem, the problem is some time it struck with any PDF file and automatically the library kills the PHP processing and restart the queue job again and again from scratch, This only happens with some specific PDF files. Please let me know what to do, My Queue job process is based on your library else if there is not any solution then I need to find some else library.

Thanks
Adil

**Comment by sebastiandedeyne** [comment]
Are you running the queue as a daemon?

**Comment by adilsaeed31** [comment]
Yes but I'm freeing the PDF object Variable from memory in loop. here is my code you can see or i can give you the demo if you want.

`
   public function handle()
    {
        echo Utility::bytesToHuman(memory_get_usage(true)) . " Job Started Object will create Now" . PHP_EOL;

        $client = new Client(env('DROPBOX_ACCESS_TOKEN', config('dropbox.access_token')), env('DROPBOX_APP_SECRET', config('dropbox.app_secret')));

        $adapter = new DropboxAdapter($client);

        $filesystem = new Filesystem($adapter);

        $Image = new Image();

        echo Utility::bytesToHuman(memory_get_usage(true)) . " All Objects are creating except PDF library Image " . PHP_EOL;

        Dropbox::where('is_process', 0)->where('type', 'file')->chunk(200, function ($dropboxArr) use ($filesystem, $Image) {
            ;

            echo Utility::bytesToHuman(memory_get_usage(true)) . " Dropbox Model Chunk Query started " . PHP_EOL;


            foreach ($dropboxArr as $row) {

                /**
                 * Art Creation Process
                 *
                 */
                echo Utility::bytesToHuman(memory_get_usage(true)) . " First Loop started with file path " . $row->path . " " . PHP_EOL;


                $art = Art::where('folder', $row->folder)->get()->first();

                if (empty($art)) {

                    $maxCode = (Art::max('code') + 1);
                    $art = [
                        'title' => $row->folder,
                        'code' => $maxCode,
                        'folder' => $row->folder
                    ];

                    Art::create($art);
                }

                echo Utility::bytesToHuman(memory_get_usage(true)) . " Art First Query process in loop " . PHP_EOL;

                /**
                 * Print Checking & Create Process
                 *
                 */

                $print = Prnt::select('id', 'title', 'code')->where('title', trim($row->filename))->get()->first();

                echo Utility::bytesToHuman(memory_get_usage(true)) . " Print 2nd Query process in loop " . PHP_EOL;


                if (empty($print)) {
                    $maxCode = (Prnt::max('code') + 1);


                    /**
                     * Link Shared Process
                     *
                     */


                    $curl = curl_init();

                    curl_setopt_array($curl, array(
                        CURLOPT_URL => "https://api.dropboxapi.com/2/sharing/create_shared_link",
                        CURLOPT_RETURNTRANSFER => true,
                        CURLOPT_ENCODING => "",
                        CURLOPT_MAXREDIRS => 10,
                        CURLOPT_TIMEOUT => 30,
                        CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
                        CURLOPT_CUSTOMREQUEST => "POST",
                        CURLOPT_POSTFIELDS => json_encode(array('path' => "/" . $row->path)),
                        CURLOPT_HTTPHEADER => array(
                            "authorization: Bearer " . env('DROPBOX_ACCESS_TOKEN', config('dropbox.access_token')),
                            "content-type: application/json"
                        ),
                    ));

                    $response = curl_exec($curl);
                    $err = curl_error($curl);

                    curl_close($curl);

                    if ($err) {

                    } else {
                        $shared_link = json_decode($response);
                    }

                    echo Utility::bytesToHuman(memory_get_usage(true)) . " Dropbox shared link generation process in loop " . PHP_EOL;

                    /**
                     * Image Creation Process
                     *
                     */

                    $fileExt = $row->extension;

                    $file = $filesystem->read(strtolower($row->path));

                    if (!empty($file)) {

                        echo Utility::bytesToHuman(memory_get_usage(true)) . " Dropbox file read process in loop " . PHP_EOL;

                        Storage::put('sync.' . $fileExt, $file);

                        $filePath = storage_path('app/sync.' . $fileExt);

                        $pdf = new Pdf($filePath);

                        echo Utility::bytesToHuman(memory_get_usage(true)) . " PDF object created in loop " . PHP_EOL;

                        $savePath = public_path('sync-mblob.jpg');

                        $pdf->saveImage($savePath);


                        $Image->make(public_path('sync-mblob.jpg'))->resize(150, 150)->save(public_path('sync-blob.jpg'));

                        /**
                         * Print Creation Process
                         *
                         */

                        $print = [
                            'title' => trim($row->filename),
                            'code' => $maxCode,
                            'sample' => file_get_contents(public_path('sync-mblob.jpg')),
                            'thumbnail' => file_get_contents(public_path('sync-blob.jpg')),
                            'preview_url' => @$shared_link->url
                        ];

                        echo Utility::bytesToHuman(memory_get_usage(true)) . " File get content method for both sample and thumb process in loop " . PHP_EOL;


                        $print = Prnt::create($print);


                        echo Utility::bytesToHuman(memory_get_usage(true)) . " Prnt record insert process in loop " . PHP_EOL;


                        $art = Art::where('folder', $row->folder)->get()->first();

                        echo Utility::bytesToHuman(memory_get_usage(true)) . " Art condition check process in loop " . PHP_EOL;

                        $art->prints()->attach([$print->id]);


                        Dropbox::where('id', $row->id)->update(['is_process' => 1]);

                        unset($pdf); //Removing the PDF Object to clear the memory consumption issue.

                        echo Utility::bytesToHuman(memory_get_usage(true)) . " PDF Object unset in loop to clear memory" . PHP_EOL;
                    } else {
                        echo Utility::bytesToHuman(memory_get_usage(true)) . " file was empty moving to next file " . PHP_EOL;
                    }
                }
            }
        });
    }
`

Note : I can provide you the demo if you want.

Thanks
Adil

**Comment by freekmurze** [comment]
Try calling  [`gc_collect_cycles`](http://php.net/manual/en/function.gc-collect-cycles.php) after `unset($pdf)` to see if that helps.

**Comment by adilsaeed31** [comment]
Hi,
Ok I'll try this in my code after unset($pdf), I found another problem , there is difference between PDF image and converted image, is it possible, to convert the pdf image exactly same as image colours.

One more thing, I'm thinking the Linux CLI conversion is faster then php conversion do you have cli command to convert pdf to image.

Please Let me know about this.

Thanks
Adil

**Comment by freekmurze** [comment]
If you investigate this issue further, let me know your findings.

Currently we  do not have an issue with the speed or image colours in our projects. 

Using (and requiring) a CLI tool to perform the conversion would be a breaking change. So a PR would probably get rejected.

**Comment by adilsaeed31** [comment]
I investigate it properly and I found an issue some of the PDF files eating all the system memory and system automatically kills it and restart it, this is only happens with some PDF files we have in Dropbox, However If you want any of these let me know I will send you but for now I'm sending you one which I tried to fig
[Ewella art 2.pdf](https://github.com/spatie/pdf-to-image/files/338939/Ewella.art.2.pdf)
ure out but got no success yet, You can try at your end to convert the file into image with same colours, then maybe you know why it's eating all the memory and hangs the server and system and why colours are different from original one.

Thanks
Adil
